In [4]:
import pandas as pd
import pylab as pl
import numpy as np
import scipy.optimize as opt
from sklearn.preprocessing import StandardScaler
%matplotlib inline 
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv("ChurnData.csv")
df.head()

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   

   longmon  ...  pager  internet  callwait  confer  ebill  loglong  logtoll  \
0     4.40  ...    1.0       0.0       1.0     1.0    0.0    1.482    3.033   
1     9.45  ...    0.0       0.0       0.0     0.0    0.0    2.246    3.240   
2     6.30  ...    0.0       0.0       0.0     1.0    0.0    1.841    3.240   
3     6.05  ...    1.0       1.0       1.0     1.0    1.0    1.800    3.807   
4     7.10  ...    0.0       0.0       1.0     1.0    0.0    1.960    3.091   

   lninc  custcat  churn  
0  4.913      4.0    1.0  
1  3.497      1.0    1.0  
2  3.401      3.0    0.0  
3  4.331      4.0    0.0  
4  4.382      3.0    0.0  

[5 rows x 28 columns]

In [6]:
df.shape

(200, 28)

In [8]:
df.columns.values

array(['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip',
       'callcard', 'wireless', 'longmon', 'tollmon', 'equipmon',
       'cardmon', 'wiremon', 'longten', 'tollten', 'cardten', 'voice',
       'pager', 'internet', 'callwait', 'confer', 'ebill', 'loglong',
       'logtoll', 'lninc', 'custcat', 'churn'], dtype=object)

In [10]:
df["churn"].value_counts()

0.0    142
1.0     58
Name: churn, dtype: int64

In [11]:
X = np.asarray(df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip']])
y = np.asarray(df["churn"])
X[:5]

array([[ 11.,  33.,   7., 136.,   5.,   5.,   0.],
       [ 33.,  33.,  12.,  33.,   2.,   0.,   0.],
       [ 23.,  30.,   9.,  30.,   1.,   2.,   0.],
       [ 38.,  35.,   5.,  76.,   2.,  10.,   1.],
       [  7.,  35.,  14.,  80.,   2.,  15.,   0.]])

In [12]:
y[:5]

array([1., 1., 0., 0., 0.])

In [13]:
ss = StandardScaler()
X = ss.fit_transform(X)
X[:5]

array([[-1.13518441, -0.62595491, -0.4588971 ,  0.4751423 ,  1.6961288 ,
        -0.58477841, -0.85972695],
       [-0.11604313, -0.62595491,  0.03454064, -0.32886061, -0.6433592 ,
        -1.14437497, -0.85972695],
       [-0.57928917, -0.85594447, -0.261522  , -0.35227817, -1.42318853,
        -0.92053635, -0.85972695],
       [ 0.11557989, -0.47262854, -0.65627219,  0.00679109, -0.6433592 ,
        -0.02518185,  1.16316   ],
       [-1.32048283, -0.47262854,  0.23191574,  0.03801451, -0.6433592 ,
         0.53441472, -0.85972695]])

In [14]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 4)
print('Train set:', x_train.shape,  y_train.shape)
print('Test set:', x_test.shape,  y_test.shape)

Train set: (150, 7) (150,)
Test set: (50, 7) (50,)


In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C = 0.01, solver = 'liblinear')
# ['liblinear', 'newton-cg', 'lbfgs', 'sag', 'saga']
# C means inverse of regularization strength. 
# Which must be a positive float. Smaller values specify stronger regularization.
LR.fit(x_train, y_train)
LR

LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [19]:
y_pred = LR.predict(x_test)
y_pred

array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0.,
       1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0.])

In [20]:
y_test

array([0., 0., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1.,
       1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
# predict_proba returns estimates for all classes, ordered by the label of classes.
y_pred_prob = LR.predict_proba(x_test)
y_pred_prob

array([[0.53660333, 0.46339667],
       [0.5968363 , 0.4031637 ],
       [0.55724495, 0.44275505],
       [0.62177417, 0.37822583],
       [0.56147901, 0.43852099],
       [0.55308698, 0.44691302],
       [0.52219413, 0.47780587],
       [0.59516065, 0.40483935],
       [0.41858953, 0.58141047],
       [0.62301346, 0.37698654],
       [0.57362406, 0.42637594],
       [0.6149623 , 0.3850377 ],
       [0.47877715, 0.52122285],
       [0.43300249, 0.56699751],
       [0.64946276, 0.35053724],
       [0.54558633, 0.45441367],
       [0.51871078, 0.48128922],
       [0.48457878, 0.51542122],
       [0.49131765, 0.50868235],
       [0.52403154, 0.47596846],
       [0.60731128, 0.39268872],
       [0.52857761, 0.47142239],
       [0.62714763, 0.37285237],
       [0.52383581, 0.47616419],
       [0.50244993, 0.49755007],
       [0.69269397, 0.30730603],
       [0.54515482, 0.45484518],
       [0.52001935, 0.47998065],
       [0.51588751, 0.48411249],
       [0.69711966, 0.30288034],
       [0.

In [28]:
from sklearn.metrics import jaccard_similarity_score
jaccard_similarity_score(y_test, y_pred)

C:\Users\SRAVAN\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:635: DeprecationWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  'and multiclass classification tasks.', DeprecationWarning)


0.78

In [36]:
from sklearn.metrics import classification_report, confusion_matrix, log_loss
confusion_matrix(y_test, y_pred, labels = [1, 0])

array([[ 7,  9],
       [ 2, 32]], dtype=int64)

In [35]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.78      0.94      0.85        34
         1.0       0.78      0.44      0.56        16

    accuracy                           0.78        50
   macro avg       0.78      0.69      0.71        50
weighted avg       0.78      0.78      0.76        50



Based on the count of each section, we can calculate precision and recall of each label:


- __Precision__ is a measure of the accuracy provided that a class label has been predicted. It is defined by: precision = TP / (TP + FP)

- __Recall__ is true positive rate. It is defined as: Recall =  TP / (TP + FN)

    
So, we can calculate precision and recall of each class.

__F1 score:__
Now we are in the position to calculate the F1 scores for each label based on the precision and recall of that label. 

The F1 score is the harmonic average of the precision and recall, where an F1 score reaches its best value at 1 (perfect precision and recall) and worst at 0. It is a good way to show that a classifer has a good value for both recall and precision.


And finally, we can tell the average accuracy for this classifier is the average of the F1-score for both labels, which is 0.72 in our case.

In [38]:
log_loss(y_test, y_pred_prob)

0.5829524462491935

In [55]:
LR2 = LogisticRegression(C=0.4, solver='sag')
LR2.fit(x_train, y_train)
y_pred_prob = LR2.predict_proba(x_test)
log_loss(y_test, y_pred_prob)

0.5361894518999559

In [56]:
y_pred = LR2.predict(x_test)

In [57]:
confusion_matrix(y_test, y_pred, labels = [1, 0])

array([[ 4, 12],
       [ 0, 34]], dtype=int64)

In [59]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.74      1.00      0.85        34
         1.0       1.00      0.25      0.40        16

    accuracy                           0.76        50
   macro avg       0.87      0.62      0.62        50
weighted avg       0.82      0.76      0.71        50

