In [1]:
#Vectorization approach
import numpy as np
import time
tic = time.time()
a = np.random.randn(1000000)
b = np.random.randn(1000000)

c = np.dot(a, b)
toc = time.time()
print("Result: ", c)
print("For Vectorization approach: " + str((toc - tic) * 1000) + "ms")

Result:  83.44374080033242
For Vectorization approach: 91.48645401000977ms


In [2]:
#Non-Vectorization approach
tic = time.time()
c = 0
for i in range(1000000):
    c += a[i] * b[i]
toc = time.time()
print("Result: ", c)
print("For Non-Vectorization approach: " + str((toc - tic) * 1000) + "ms")

Result:  83.44374080037562
For Non-Vectorization approach: 549.5309829711914ms


In [3]:
1266.2537097930908 / 126.98173522949219

9.971935786706721

In [4]:
print("Vectorized approach is 10x(minimum) faster than the non vectorized approach")

Vectorized approach is 10x(minimum) faster than the non vectorized approach


In [21]:
# Non - vectorized approach
import math

tic = time.time()
u = np.zeros((1000000, 1))
v = np.random.randn(1000000)
for i in range(1000000):
    u[i] = math.exp(v[i])

toc = time.time()
print(u)
print("For Non-Vectorization approach: " + str((toc - tic) * 1000) + "ms")

[[0.5158011 ]
 [1.60854987]
 [1.60032529]
 ...
 [0.8905168 ]
 [2.32919271]
 [0.24152215]]
For Non-Vectorization approach: 551.5305995941162ms


In [22]:
# Vectorized approach
tic = time.time()
u = np.exp(v)
toc = time.time()
print(u)
print("For Vectorization approach: " + str((toc - tic) * 1000) + "ms")

[0.5158011  1.60854987 1.60032529 ... 0.8905168  2.32919271 0.24152215]
For Vectorization approach: 8.97526741027832ms


In [23]:
551.5305995941162/8.97526741027832

61.45004648691725

In [24]:
print("Vectorized approach is 60x(minimum) faster than the non vectorized approach")

Vectorized approach is 60x(minimum) faster than the non vectorized approach


In [32]:
np.exp([1,2,3,4])

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

## Broadcasting

In [1]:
import numpy as np
A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [6]:
cal = np.sum(A, axis = 0)
cal

array([ 59. , 239. , 155.4,  76.9])

In [8]:
percentage = (A/cal)*100
percentage

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

In [10]:
sample = np.random.randn(6)
sample

array([-0.0134173 ,  0.38688972,  0.70197268, -0.26105185,  1.13263685,
       -0.30275711])

In [11]:
sample.reshape(3,2)

array([[-0.0134173 ,  0.38688972],
       [ 0.70197268, -0.26105185],
       [ 1.13263685, -0.30275711]])

### Note on python - Numpy vectors

In [13]:
# Do not use these sort of arrays
a = np.random.randn(5)
a.shape

(5,)

In [16]:
print(a.T)
print(a)

[-0.13839715 -0.4000149   1.02879154 -0.06493428  1.06131535]
[-0.13839715 -0.4000149   1.02879154 -0.06493428  1.06131535]


In [17]:
np.dot(a, a.T)

2.3681844434366512

In [19]:
# Use these sort of arrays
a = np.random.randn(5, 1)
a.shape

(5, 1)

In [20]:
print(a)
print(a.T)

[[-0.15914798]
 [-0.89377569]
 [ 1.30448557]
 [-0.13001054]
 [-0.55831956]]
[[-0.15914798 -0.89377569  1.30448557 -0.13001054 -0.55831956]]


In [21]:
np.dot(a, a.T)

array([[ 0.02532808,  0.14224259, -0.20760624,  0.02069091,  0.08885543],
       [ 0.14224259,  0.79883498, -1.16591748,  0.11620026,  0.49901245],
       [-0.20760624, -1.16591748,  1.70168259, -0.16959687, -0.7283198 ],
       [ 0.02069091,  0.11620026, -0.16959687,  0.01690274,  0.07258743],
       [ 0.08885543,  0.49901245, -0.7283198 ,  0.07258743,  0.31172073]])