In [2]:
from keras.applications.resnet50 import ResNet50
from keras.preprocessing import image
from keras.applications.resnet50 import preprocess_input, decode_predictions

In [4]:
model = ResNet50(weights = 'imagenet')

### Image used for detecting
<img src="https://i.pinimg.com/originals/1c/2f/52/1c2f52962906d49ee2c3359a23de64e1.jpg" height = 400 width = 400>

In [7]:
img_path = 'sample.jpg'

In [10]:
img = image.load_img(img_path, target_size=(224, 224))

In [11]:
x = image.img_to_array(img)
x

array([[[ 56., 119., 160.],
        [ 54., 116., 157.],
        [ 59., 118., 160.],
        ...,
        [ 94., 133., 166.],
        [ 98., 137., 170.],
        [ 95., 134., 167.]],

       [[ 55., 117., 158.],
        [ 55., 117., 158.],
        [ 54., 113., 155.],
        ...,
        [ 97., 136., 169.],
        [ 93., 132., 165.],
        [ 95., 134., 167.]],

       [[ 54., 116., 157.],
        [ 54., 116., 157.],
        [ 54., 113., 155.],
        ...,
        [ 97., 136., 167.],
        [ 95., 134., 165.],
        [ 97., 136., 167.]],

       ...,

       [[216., 180.,  83.],
        [145., 100.,  45.],
        [215., 177.,  80.],
        ...,
        [144.,  97.,  25.],
        [174., 136.,  74.],
        [141.,  92.,  33.]],

       [[235., 197.,  98.],
        [165., 120.,  61.],
        [209., 171.,  74.],
        ...,
        [169., 121.,  49.],
        [167., 127.,  66.],
        [144.,  94.,  35.]],

       [[235., 196.,  93.],
        [174., 130.,  59.],
        [202., 1

In [13]:
import numpy as np
x = np.expand_dims(x, axis = 0)
x

array([[[[ 56., 119., 160.],
         [ 54., 116., 157.],
         [ 59., 118., 160.],
         ...,
         [ 94., 133., 166.],
         [ 98., 137., 170.],
         [ 95., 134., 167.]],

        [[ 55., 117., 158.],
         [ 55., 117., 158.],
         [ 54., 113., 155.],
         ...,
         [ 97., 136., 169.],
         [ 93., 132., 165.],
         [ 95., 134., 167.]],

        [[ 54., 116., 157.],
         [ 54., 116., 157.],
         [ 54., 113., 155.],
         ...,
         [ 97., 136., 167.],
         [ 95., 134., 165.],
         [ 97., 136., 167.]],

        ...,

        [[216., 180.,  83.],
         [145., 100.,  45.],
         [215., 177.,  80.],
         ...,
         [144.,  97.,  25.],
         [174., 136.,  74.],
         [141.,  92.,  33.]],

        [[235., 197.,  98.],
         [165., 120.,  61.],
         [209., 171.,  74.],
         ...,
         [169., 121.,  49.],
         [167., 127.,  66.],
         [144.,  94.,  35.]],

        [[235., 196.,  93.],
       

In [14]:
x = preprocess_input(x)

In [15]:
model.predict(x)

array([[7.73086525e-11, 2.24807395e-10, 5.02003827e-10, 3.47700063e-10,
        1.08277470e-10, 1.36518929e-09, 1.14274468e-09, 1.65161858e-08,
        3.36581873e-09, 3.22571019e-08, 1.46016033e-09, 1.88028704e-09,
        3.82254406e-09, 5.38209033e-10, 7.41479322e-10, 2.42828802e-09,
        6.56534715e-10, 1.49850377e-09, 3.98434308e-09, 7.40868589e-10,
        7.00768998e-10, 6.35018538e-10, 3.75031828e-09, 9.71978267e-08,
        4.29985398e-08, 3.12404824e-10, 8.30479241e-10, 6.68559874e-10,
        4.03080708e-10, 1.51340759e-10, 2.92063262e-10, 1.72296136e-10,
        5.01570341e-10, 1.88820093e-09, 1.67835024e-09, 6.45261067e-10,
        6.73125222e-10, 1.06838559e-10, 6.57499666e-10, 3.19220472e-09,
        3.36029399e-10, 9.82804615e-10, 6.92692304e-09, 3.94559274e-09,
        4.42327869e-10, 4.05203071e-09, 4.21857327e-10, 2.48143461e-09,
        1.83450000e-09, 2.40315390e-09, 3.18876481e-10, 4.84719209e-10,
        3.45764972e-10, 1.15124599e-09, 9.39625044e-10, 6.058903

In [18]:
decode_predictions(model.predict(x), top = 3)[0]

[('n02129165', 'lion', 0.9995474),
 ('n02130308', 'cheetah', 0.00022837792),
 ('n07802026', 'hay', 3.8701568e-05)]