In [2]:
import numpy as np
np.random.seed(17)

from keras.models import Sequential
from keras.layers import Dense, Embedding, Flatten, Input
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.optimizers import Adam
from sklearn.preprocessing import OneHotEncoder

In [10]:
docs = ['rohit is my favourite cricketer', 'he plays pull shot very very well', 'i like his captaincy very much',
       'he is very calm and composed', '2019 is my memorable year of rohit sharma']

In [4]:
vocab_size = 100

In [18]:
one_hot(docs[1], 100)

[69, 5, 2, 3, 76, 76, 81]

In [14]:
oh = np.array(one_hot(docs[1], vocab_size)).reshape(-1, 1)
oh

array([[69],
       [ 5],
       [ 2],
       [ 3],
       [76],
       [76],
       [81]])

In [20]:
enc = OneHotEncoder()
enc.fit(np.array(range(100)).reshape(-1, 1))

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='error', sparse=True)

In [23]:
oh_enc = enc.transform(oh).toarray()
oh_enc

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.

In [24]:
encoded_docs = [one_hot(d, vocab_size) for d in docs]
encoded_docs

[[71, 53, 24, 15, 44],
 [69, 5, 2, 3, 76, 76, 81],
 [94, 11, 17, 34, 76, 52],
 [69, 53, 76, 57, 85, 84],
 [83, 53, 24, 18, 30, 89, 71, 79]]

In [25]:
max_length = 24
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
padded_docs

array([[71, 53, 24, 15, 44,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0],
       [69,  5,  2,  3, 76, 76, 81,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0],
       [94, 11, 17, 34, 76, 52,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0],
       [69, 53, 76, 57, 85, 84,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0],
       [83, 53, 24, 18, 30, 89, 71, 79,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0]])

In [26]:
tuples = np.empty((0, 2))
for padded_doc in padded_docs:
    length = len(padded_doc)
    for i in range(length):
        if padded_doc[i] != 0:
            if i<length-1 & padded_doc[i+1] != 0:
                tuples = np.append(tuples, [[padded_doc[i],padded_doc[i+1]]], axis=0) 
                if i<length-2 & padded_doc[i+2] != 0:
                    tuples = np.append(tuples, [[padded_doc[i],padded_doc[i+2]]], axis=0) 
            if i > 0:
                tuples = np.append(tuples, [[padded_doc[i],padded_doc[i-1]]], axis=0) 
                if i > 1:
                    tuples = np.append(tuples, [[padded_doc[i],padded_doc[i-2]]], axis=0) 

    
print (tuples.shape)
tuples

(94, 2)


array([[71., 53.],
       [71., 24.],
       [53., 24.],
       [53., 15.],
       [53., 71.],
       [24., 15.],
       [24., 44.],
       [24., 53.],
       [24., 71.],
       [15., 44.],
       [15., 24.],
       [15., 53.],
       [44., 15.],
       [44., 24.],
       [69.,  5.],
       [69.,  2.],
       [ 5.,  2.],
       [ 5.,  3.],
       [ 5., 69.],
       [ 2.,  3.],
       [ 2., 76.],
       [ 2.,  5.],
       [ 2., 69.],
       [ 3., 76.],
       [ 3., 76.],
       [ 3.,  2.],
       [ 3.,  5.],
       [76.,  3.],
       [76.,  2.],
       [76., 81.],
       [76., 76.],
       [76.,  3.],
       [81., 76.],
       [81., 76.],
       [94., 11.],
       [94., 17.],
       [11., 17.],
       [11., 34.],
       [11., 94.],
       [17., 11.],
       [17., 94.],
       [34., 76.],
       [34., 52.],
       [34., 17.],
       [34., 11.],
       [76., 52.],
       [76., 34.],
       [76., 17.],
       [52., 76.],
       [52., 34.],
       [69., 53.],
       [69., 76.],
       [53.,

In [27]:
onehotlabels_x = enc.transform(tuples[:,0].reshape(-1, 1)).toarray()

print  (onehotlabels_x.shape)
print ('---')
print (onehotlabels_x)
print ('---')
print (onehotlabels_x[0])

(94, 100)
---
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
---
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


In [28]:

onehotlabels_y = enc.transform(tuples[:,1].reshape(-1, 1)).toarray()

print  (onehotlabels_y.shape)
print ('---')
print (onehotlabels_y)
print ('---')
print (onehotlabels_y[0])

(94, 100)
---
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
---
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


In [32]:
model = Sequential()

input = Dense(100, input_shape=(100,), activation='relu')
model.add(input)
bottleneck = Dense(2, activation='relu')
model.add(bottleneck)
model.add(Dense(100, activation='softmax'))
# compile the model
model.compile(optimizer="adam", loss='binary_crossentropy', metrics=['acc'])
# summarize the model
print(model.summary())

# fit the model
model.fit(onehotlabels_x, onehotlabels_y, epochs=500, verbose=1)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_10 (Dense)             (None, 100)               10100     
_________________________________________________________________
dense_11 (Dense)             (None, 2)                 202       
_________________________________________________________________
dense_12 (Dense)             (None, 100)               300       
Total params: 10,602
Trainable params: 10,602
Non-trainable params: 0
_________________________________________________________________
None

Epoch 1/500
94/94 [==============================] - 1s 9ms/step - loss: 0.0560 - acc: 0.9900
Epoch 2/500
94/94 [==============================] - 0s 244us/step - loss: 0.0560 - acc: 0.9900
Epoch 3/500
94/94 [==============================] - 0s 213us/step - loss: 0.0559 - acc: 0.9900
Epoch 4/500
94/94 [==============================] - 0s 244us/step - loss: 0.0559 - acc: 0.9900
Epoch 5/500
94

94/94 [==============================] - 0s 297us/step - loss: 0.0398 - acc: 0.9900
Epoch 76/500
94/94 [==============================] - 0s 181us/step - loss: 0.0397 - acc: 0.9900
Epoch 77/500
94/94 [==============================] - 0s 159us/step - loss: 0.0397 - acc: 0.9900
Epoch 78/500
94/94 [==============================] - 0s 127us/step - loss: 0.0396 - acc: 0.9900
Epoch 79/500
94/94 [==============================] - 0s 85us/step - loss: 0.0396 - acc: 0.9900
Epoch 80/500
94/94 [==============================] - 0s 117us/step - loss: 0.0395 - acc: 0.9900
Epoch 81/500
94/94 [==============================] - 0s 126us/step - loss: 0.0395 - acc: 0.9900
Epoch 82/500
94/94 [==============================] - 0s 149us/step - loss: 0.0395 - acc: 0.9900
Epoch 83/500
94/94 [==============================] - 0s 74us/step - loss: 0.0394 - acc: 0.9900
Epoch 84/500
94/94 [==============================] - 0s 127us/step - loss: 0.0394 - acc: 0.9900
Epoch 85/500
94/94 [=========================

94/94 [==============================] - 0s 128us/step - loss: 0.0371 - acc: 0.9902
Epoch 160/500
94/94 [==============================] - 0s 127us/step - loss: 0.0371 - acc: 0.9902
Epoch 161/500
94/94 [==============================] - 0s 212us/step - loss: 0.0370 - acc: 0.9902
Epoch 162/500
94/94 [==============================] - 0s 106us/step - loss: 0.0370 - acc: 0.9902
Epoch 163/500
94/94 [==============================] - 0s 159us/step - loss: 0.0370 - acc: 0.9902
Epoch 164/500
94/94 [==============================] - 0s 223us/step - loss: 0.0370 - acc: 0.9902
Epoch 165/500
94/94 [==============================] - 0s 122us/step - loss: 0.0369 - acc: 0.9902
Epoch 166/500
94/94 [==============================] - 0s 170us/step - loss: 0.0369 - acc: 0.9902
Epoch 167/500
94/94 [==============================] - 0s 138us/step - loss: 0.0369 - acc: 0.9900
Epoch 168/500
94/94 [==============================] - 0s 180us/step - loss: 0.0368 - acc: 0.9902
Epoch 169/500
94/94 [=============

94/94 [==============================] - 0s 233us/step - loss: 0.0346 - acc: 0.9902
Epoch 243/500
94/94 [==============================] - 0s 106us/step - loss: 0.0345 - acc: 0.9902
Epoch 244/500
94/94 [==============================] - 0s 244us/step - loss: 0.0345 - acc: 0.9902
Epoch 245/500
94/94 [==============================] - 0s 169us/step - loss: 0.0345 - acc: 0.9902
Epoch 246/500
94/94 [==============================] - 0s 138us/step - loss: 0.0345 - acc: 0.9902
Epoch 247/500
94/94 [==============================] - 0s 149us/step - loss: 0.0344 - acc: 0.9902
Epoch 248/500
94/94 [==============================] - 0s 233us/step - loss: 0.0344 - acc: 0.9902
Epoch 249/500
94/94 [==============================] - 0s 340us/step - loss: 0.0344 - acc: 0.9902
Epoch 250/500
94/94 [==============================] - 0s 180us/step - loss: 0.0343 - acc: 0.9902
Epoch 251/500
94/94 [==============================] - 0s 244us/step - loss: 0.0343 - acc: 0.9902
Epoch 252/500
94/94 [=============

94/94 [==============================] - 0s 96us/step - loss: 0.0324 - acc: 0.9902
Epoch 326/500
94/94 [==============================] - 0s 117us/step - loss: 0.0323 - acc: 0.9902
Epoch 327/500
94/94 [==============================] - 0s 125us/step - loss: 0.0323 - acc: 0.9902
Epoch 328/500
94/94 [==============================] - 0s 106us/step - loss: 0.0323 - acc: 0.9902
Epoch 329/500
94/94 [==============================] - 0s 106us/step - loss: 0.0323 - acc: 0.9902
Epoch 330/500
94/94 [==============================] - 0s 106us/step - loss: 0.0323 - acc: 0.9902
Epoch 331/500
94/94 [==============================] - 0s 127us/step - loss: 0.0322 - acc: 0.9902
Epoch 332/500
94/94 [==============================] - 0s 74us/step - loss: 0.0322 - acc: 0.9902
Epoch 333/500
94/94 [==============================] - 0s 117us/step - loss: 0.0322 - acc: 0.9902
Epoch 334/500
94/94 [==============================] - 0s 127us/step - loss: 0.0322 - acc: 0.9902
Epoch 335/500
94/94 [===============

94/94 [==============================] - 0s 95us/step - loss: 0.0310 - acc: 0.9902
Epoch 409/500
94/94 [==============================] - 0s 85us/step - loss: 0.0310 - acc: 0.9902
Epoch 410/500
94/94 [==============================] - 0s 138us/step - loss: 0.0309 - acc: 0.9902
Epoch 411/500
94/94 [==============================] - 0s 180us/step - loss: 0.0309 - acc: 0.9902
Epoch 412/500
94/94 [==============================] - 0s 96us/step - loss: 0.0309 - acc: 0.9902
Epoch 413/500
94/94 [==============================] - 0s 74us/step - loss: 0.0309 - acc: 0.9902
Epoch 414/500
94/94 [==============================] - 0s 95us/step - loss: 0.0309 - acc: 0.9902
Epoch 415/500
94/94 [==============================] - 0s 85us/step - loss: 0.0309 - acc: 0.9902
Epoch 416/500
94/94 [==============================] - 0s 159us/step - loss: 0.0309 - acc: 0.9902
Epoch 417/500
94/94 [==============================] - 0s 128us/step - loss: 0.0309 - acc: 0.9902
Epoch 418/500
94/94 [===================

Epoch 492/500
94/94 [==============================] - 0s 148us/step - loss: 0.0301 - acc: 0.9902
Epoch 493/500
94/94 [==============================] - 0s 116us/step - loss: 0.0301 - acc: 0.9902
Epoch 494/500
94/94 [==============================] - 0s 159us/step - loss: 0.0301 - acc: 0.9902
Epoch 495/500
94/94 [==============================] - 0s 74us/step - loss: 0.0301 - acc: 0.9902
Epoch 496/500
94/94 [==============================] - 0s 127us/step - loss: 0.0301 - acc: 0.9902
Epoch 497/500
94/94 [==============================] - 0s 148us/step - loss: 0.0301 - acc: 0.9902
Epoch 498/500
94/94 [==============================] - 0s 85us/step - loss: 0.0301 - acc: 0.9902
Epoch 499/500
94/94 [==============================] - 0s 104us/step - loss: 0.0301 - acc: 0.9902
Epoch 500/500
94/94 [==============================] - 0s 149us/step - loss: 0.0301 - acc: 0.9902


In [33]:
model = Sequential()
model.add(input)
model.add(bottleneck)
model.compile(optimizer=Adam(lr=0.001), loss='binary_crossentropy', metrics=['acc'])
test = model.predict(oh_enc)
print (test)

[[21.118444 27.723824]
 [21.648916 27.581942]
 [20.203487 29.390535]
 [17.395046 33.003128]
 [ 5.299002 11.570113]
 [ 5.299002 11.570113]
 [12.935149 44.982475]]


In [34]:
model = Sequential()
model.add(Embedding(1000, 2, input_length=5))
model.compile('rmsprop', 'mse')

input_array = np.random.randint(1000, size=(12, 5)) # 12 documents, 5 words per document
input_array

array([[980, 287, 567, 209, 977],
       [741,  18, 302, 982, 529],
       [355,  36, 591, 627, 634],
       [376,  51, 240, 675, 443],
       [489, 544, 748, 306, 151],
       [739, 580, 362,  39, 943],
       [139, 711, 802, 917, 590],
       [696, 589, 942, 676, 466],
       [ 78, 516, 376, 446, 511],
       [373,  91, 733, 161, 940],
       [112, 485, 255, 169, 235],
       [503, 436,   5, 508, 631]])

In [35]:
output_array = model.predict(input_array)
print (output_array.shape)
print (output_array)

(12, 5, 2)
[[[-0.04568199  0.01308122]
  [ 0.01892569 -0.0300342 ]
  [-0.04771891 -0.02760842]
  [ 0.0363226  -0.00876169]
  [ 0.02772751 -0.04396896]]

 [[ 0.00810627  0.02977685]
  [-0.02512401 -0.0117013 ]
  [ 0.04803199 -0.02802942]
  [ 0.03104891 -0.02968789]
  [ 0.01926723 -0.00979995]]

 [[ 0.02673724  0.04495323]
  [-0.04031041 -0.04872468]
  [ 0.0349363  -0.04728299]
  [-0.02198076 -0.02794137]
  [-0.03352576  0.02154993]]

 [[ 0.01823131 -0.03204508]
  [-0.03456756 -0.03841591]
  [ 0.01602293  0.04204187]
  [ 0.04292743 -0.04371952]
  [-0.00667838 -0.03734802]]

 [[ 0.02437163  0.04016806]
  [ 0.01205482 -0.04893918]
  [ 0.01633265 -0.04092263]
  [-0.04946796 -0.01331349]
  [ 0.03090651 -0.01419378]]

 [[-0.04877987  0.00803237]
  [ 0.01659952 -0.01499069]
  [-0.01599232  0.01150848]
  [-0.04262859 -0.02148805]
  [ 0.04896236  0.00886571]]

 [[-0.02867601  0.03778097]
  [-0.01228908  0.00553318]
  [-0.01745237  0.00543827]
  [ 0.04384542 -0.03566603]
  [-0.0032943  -0.0261903

In [36]:
docs = ['Well done!',
'Good work',
'Great effort',
'nice work',
'Excellent!',
'Really Weak',
'Poor effort!',
'not good',
'poor work',
'Could have done better.']
# define class labels
labels = [1,1,1,1,1,0,0,0,0,0]

In [37]:
vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

[[9, 29], [7, 27], [31, 19], [38, 27], [39], [19, 45], [22, 19], [1, 7], [22, 27], [38, 45, 29, 11]]


In [38]:
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

[[ 9 29  0  0]
 [ 7 27  0  0]
 [31 19  0  0]
 [38 27  0  0]
 [39  0  0  0]
 [19 45  0  0]
 [22 19  0  0]
 [ 1  7  0  0]
 [22 27  0  0]
 [38 45 29 11]]


In [39]:
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
# summarize the model
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 4, 8)              400       
_________________________________________________________________
flatten_1 (Flatten)          (None, 32)                0         
_________________________________________________________________
dense_13 (Dense)             (None, 1)                 33        
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________
None


In [40]:
model.fit(padded_docs, labels, epochs=50, verbose=0)
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 89.999998


In [41]:
import numpy as np
np.hstack((model.predict(padded_docs),np.array(labels).reshape(10,1)))

array([[0.56936693, 1.        ],
       [0.55144387, 1.        ],
       [0.54109126, 1.        ],
       [0.54073042, 1.        ],
       [0.54267347, 1.        ],
       [0.47346258, 0.        ],
       [0.49716499, 0.        ],
       [0.46410942, 0.        ],
       [0.50086576, 0.        ],
       [0.44499189, 0.        ]])